### ISSUE TITLE
Cannot install on NixOS due to outdated Node.js

### ISSUE THREAD

**Issue by Darkflicker** [ananthakumaran/paisa#343]
**Describe your Environment**
OS: NixOS unstable
Paisa Version: 0.7.3
App Variant: CLI

**Describe the bug**
Doesn't install on NixOS unstable anymore as Node.js 18 has been removed from the repo.

**To Reproduce**
1. Try to install Paisa on NixOS unstable.

**Comment by ananthakumaran** [comment]
should be fixed on master now

**Comment by Darkflicker** [comment]
Still cannot build due to npm errors.  Also, the `vendorHash` is wrong.

**Comment by bhankas** [comment]
I'm getting the hash error still:

```
error: hash mismatch in fixed-output derivation '/nix/store/l9wn4px95dlk0g0vkxisgsxccbj2k8sq-paisa-cli-0.7.3-go-modules.drv':
        likely URL: (unknown)
         specified: sha256-KnHJ6+aMahTeNdbRcRAgBERGVYen/tM/tDcFI/NyLdE=
            got:    sha256-5jrxI+zSKbopGs5GmGVyqQcMHNZJbCsiFEH/LPXWxpk=
error: 1 dependencies of derivation '/nix/store/60q0qjlx1qn3krwzr5yna003mv84b9xk-paisa-cli-0.7.3.drv' failed to build
```

**Comment by Darkflicker** [comment]
It works on NixOS again. Thanks for the fixes.
